### ISSUE TITLE
Please, enable github pages for the documentation

### ISSUE THREAD

**Issue by svetlyak40wt** [noffle/cl-flat-tree#1]
api.html should be moved to the docs/index.html and github pages should be enabled for the repository. It will make docs available at https://noffle.github.io/cl-flat-tree

While it is not done, nice rendered documentation can be viewed via this URL:

https://htmlpreview.github.io/?https://raw.githubusercontent.com/noffle/cl-flat-tree/master/api.html

**Comment by hackergrrl** [comment]
Thanks for the idea. I've enabled github pages, and you can find the documentation here: https://noffle.github.io/cl-flat-tree/

For some reason though, the trailing slash is necessary? I get a 404 for https://noffle.github.io/cl-flat-tree

**Comment by svetlyak40wt** [comment]
It works for me without slash (doing redirect)

**Comment by hackergrrl** [comment]
Works for me now too! It might have been a delay with github pages refreshing.
