### ISSUE TITLE
Probably take some code snippets from the #poftheday to illustrate README

### ISSUE THREAD

**Issue by svetlyak40wt** [noffle/cl-flat-tree#2]
I wrote a post about cl-flat-tree:

https://40ants.com/lisp-project-of-the-day/2020/08/0167-cl-flat-tree.html

Probably it can be used to improve the documentation.

**Comment by svetlyak40wt** [comment]
Kira, it is also will be nice if you will tell to the readers of my blog a short story how does "flat tree" used in the Dat Project! I sure, it should be very interesting.

**Comment by hackergrrl** [comment]
Aw, thanks for featuring this package!

I think what you linked to (the Dat documentation) is a good summary of the data structure. Really, this module is just a very tiny piece of the larger ecosystem of packages necessary to implement the Dat protocol.
